apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: rest-demo
  name: rest-demo
  namespace: makzak65-dev
spec:
  replicas: 1
  selector:
    app: rest-demo
  template:
    metadata:
      labels:
        app: rest-demo
    spec:
      containers:
#        - env:
#            - name: PROFILE
#              value: dev
        - name: rest-demo
          image: http://0.0.0.0:8082/repository/docker-release/rest-demo:latest
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 0.2
              memory: 1Gi
          volumeMounts:
            - mountPath: /etc/my-app.conf
              name: my-app-config-prop
              subPath: application.properties
      volumes:
        - configMap:
#              defaultMode: 420
            name: my-app-config
          name: my-app-config-prop
triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
        - gds
      from:
        kind: ImageStreamTag
        name: 'rest-demo:latest'
    type: ImageChange